name: Check code formatting

concurrency:
    group: format-${{ github.head_ref }}
    cancel-in-progress: true

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:
        # The type of runner that the job will run on
        name: Check Code Formatting
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - name: Download tools
              run: |
                  sudo apt-get update && sudo apt-get install clang-format-14
                  echo "Clang-format version"
                  clang-format --version
                  wget https://raw.githubusercontent.com/Sarcasm/run-clang-format/master/run-clang-format.py
                  chmod +x ./run-clang-format.py

            - name: Test
              run: ./run-clang-format.py -r src
